---
- name: stop minecraft-forged
  service:
    name: minecraft-forged
    state: stopped
  ignore_errors: yes

- name: download minecraft-forge installer
  get_url:
    url: https://files.minecraftforge.net/maven/net/minecraftforge/forge/{{ forge_version }}/forge-{{ forge_version }}-installer.jar
    dest: "{{ forge_path }}/forge-{{ forge_version }}-installer.jar"
    mode: 0755
    force: yes

- name: download minecraft-forge universal
  get_url:
    url: https://files.minecraftforge.net/maven/net/minecraftforge/forge/{{ forge_version }}/forge-{{ forge_version }}-universal.jar
    dest: "{{ forge_path }}/forge-{{ forge_version }}-universal.jar"
    mode: 0755
    force: yes

- name: install minecraft-forge
  command: "java -jar {{ forge_path }}/forge-{{ forge_version }}-installer.jar nogui --installServer"

- name: put minecraft-forged
  template:
    src: minecraft-forged.sh.j2
    dest: /etc/init.d/minecraft-forged
    mode: 0755

- name: put minecraft-forged.service for systemd
  template:
    src: minecraft-forged.service.j2
    dest: "/etc/systemd/system/minecraft-forged.service"
    mode: 0755
  when: ansible_service_mgr == 'systemd'

- name: start minecraft-forged
  service:
    name: minecraft-forged
    state: started
