#   _                   _                      _
#  | |_ _ __ __ ___   _(_)___  _   _ _ __ ___ | |
#  | __| '__/ _` \ \ / / / __|| | | | '_ ` _ \| |
#  | |_| | | (_| |\ V /| \__ \| |_| | | | | | | |
# (_)__|_|  \__,_| \_/ |_|___(_)__, |_| |_| |_|_|
#                              |___/
#

language: python

python:
  - 3.8

os:
  - centos 7
  - centos 8
  - ubuntu 20.04

install:
  - pip install ansible

script:
  - ansible-playbook main.yml -i inventory/test-hosts.yml

sudo: required
