---
- hosts: minecraft_server
  become: yes
  become_user: root
  roles:
    - swapfile
    - screen
    - java
    - minecraft

- hosts: forge_server
  become: yes
  become_user: root
  roles:
    - swapfile
    - screen
    - java
    - minecraft
    - forge