---
# This file use to run CI.
all:
  hosts:
  children:
    minecraft_server:
      hosts:
      vars:
    forge_server:
      hosts:
        MinecraftServer:
          ansible_host: localhost
          ansible_connection: local
      vars:
  vars:
    java_version_ubuntu: 18
    minecraft_version_hex: e00c4052dac1d59a1188b2aa9d5a87113aaf1122 # 1.19
