---
- name: stop minecraftd
  service:
    name: minecraftd
    state: stopped
  ignore_errors: yes

- name: make directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ minecraft_path }}"
    - "{{ minecraft_path }}/tmp"

- name: download minecraft
  get_url:
    url: "https://launcher.mojang.com/v1/objects/{{ minecraft_version_hex }}/server.jar"
    dest: "{{ minecraft_path }}/server.jar"
    mode: 0755
    force: yes

- name: put minecraftd for init.d
  template:
    src: minecraftd.sh.j2
    dest: "/etc/init.d/minecraftd"
    mode: 0755

- name: put minecraftd.service for systemd
  template:
    src: minecraftd.service.j2
    dest: "/etc/systemd/system/minecraftd.service"
    mode: 0755
  when: ansible_service_mgr == 'systemd'

- name: enable minecraftd
  service:
    name: minecraftd
    enabled: yes

- name: start minecraftd
  service:
    name: minecraftd
    state: started

- name: put server.properties
  template:
    src: server.properties.j2
    dest: "{{ minecraft_path }}/server.properties"
    mode: 0644

- name: put eula.txt
  template:
    src: eula.txt.j2
    dest: "{{ minecraft_path }}/eula.txt"
    mode: 0644

- name: restart minecraftd
  service:
    name: minecraftd
    state: restarted