---
- name: disable swap
  command: swapoff /swapfile
  ignore_errors: yes

- name: make swapfile
  command: "dd if=/dev/zero of=/swapfile bs={{ swap_block_size }} count={{ swap_block_count }}"

- name: change swapfile permission
  file:
      path: /swapfile
      mode: 0600

- name: make swap
  command: mkswap /swapfile

- name: enable swap
  command: swapon /swapfile

- name: edit fstab
  command: sed -i -e '$a/swapfile swap swap defaults 0 0' /etc/fstab
