---
- name: install jdk on Amazon Linux
  package:
    name: "java-{{ java_version_amazon }}-openjdk.x86_64"
    state: latest
  when: ansible_facts['distribution'] == 'Amazon'

- name: install jdk on Cent OS
  package:
    name: "java-{{ java_version_centos }}-openjdk.x86_64"
    state: latest
  when: ansible_facts['distribution'] == 'CentOS'

- name: install jdk on Debian
  package:
    name: "openjdk-{{ java_version_debian }}-jdk"
    state: latest
  when: ansible_facts['distribution'] == 'Debian'
